
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/environment_ucb_db
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            required: false
chaos:
  monkey:
    enabled: true
    watcher:
      service: false
      controller: false
      repository: false
      restController: true
    assaults:
      level: 10
      latencyActive: true
      latencyRangeStart: 1000
      latencyRangeEnd: 3000
      exceptionsActive: true
server:
  port: 8080